name: Docker Image CI

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check if update available
      id: check
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: alpine:latest
        image: linux8a/nfs-server:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: steps.check.outputs.needs-updating == 'true'

    - name: Build the Docker image
      run: |
         cd dockerfile
         docker build . --file Dockerfile --tag linux8a/nfs-server:$(date +%s)
         tag=`docker images | grep nfs-server | awk '{printf $1 ":" $2}'`
         docker push $tag
         docker tag $tag linux8a/nfs-server:latest
         docker push linux8a/nfs-server:latest
      if: steps.check.outputs.needs-updating == 'true'
